### PR TITLE
Fix non implemented methods search result

### PR DESCRIPTION
**Pull request by jenow**
## What does this PR do ?

There is missing implementation on the search_result class.

```
/mnt/build/android/app/src/main/obj/local/arm64-v8a/objs/kuzzle/__/__/__/__/__/__/kcore_wrap.o: In function `Java_io_kuzzle_sdk_kuzzlesdkJNI_new_1SpecificationSearchResult':
/mnt/build/android/app/src/main/jni/../../../../../../kcore_wrap.cxx:81434: undefined reference to `kuzzleio::SpecificationSearchResult::SpecificationSearchResult(kuzzleio::search_result const*)'
/mnt/build/android/app/src/main/obj/local/arm64-v8a/objs/kuzzle/__/__/__/__/__/__/kcore_wrap.o: In function `Java_io_kuzzle_sdk_kuzzlesdkJNI_SpecificationSearchResult_1next':
/mnt/build/android/app/src/main/jni/../../../../../../kcore_wrap.cxx:81619: undefined reference to `kuzzleio::SpecificationSearchResult::next() const'
```

### CODE REVIEW

**Comment by benoitvidis** [comment]
yes @Aschen , this is a relicate and can be removed.

**Comment by scottinet** [comment]
@jenow > I think that I have already made that PR's changes in my own stability PR (as well as using smart pointers for search results). 
Can you check that this PR is still relevant?

**Comment by Aschen** [comment]
@scottinet We need at least to keep the method signature from this PR
```
            size_t total() const;
            size_t fetched() const;
            const std::string& aggregations() const;
            const std::string& hits() const;
            const std::string& scroll_id() const;
```
And we can also remove the `SpecificationSearchResult` class

**Comment by scottinet** [comment]
@Aschen > the getters you're linking are already there: https://github.com/kuzzleio/sdk-cpp/blob/1-dev/include/internal/search_result.hpp#L27

**Comment by Aschen** [comment]
> @Aschen > the getters you're linking are already there: https://github.com/kuzzleio/sdk-cpp/blob/1-dev/include/internal/search_result.hpp#L27

Yes they are here but the return type is wrong

**Comment by scottinet** [comment]
Returning the base value of the underlying C struct prevents us from the unnecessary overhead of allocating a new string class where it may not be used, at no cost for the user: `std::string` variables can be instantiated naturally with `const char*` values.

To me, our getters are correct, we do not need more than that.

**Comment by jenow** [comment]
> @jenow > I think that I have already made that PR's changes in my own stability PR (as well as using smart pointers for search results).
> Can you check that this PR is still relevant?

The SpecificationSearchResult is still not implemented anywhere: https://github.com/kuzzleio/sdk-cpp/blob/1-dev/include/internal/search_result.hpp#L40
Also as Benoit said we do not use SpecificationSearchResult, so do I remove it on this PR?

**Comment by scottinet** [comment]
We can make a PR specifically to remove that unneeded class. Or in this one. What's most convenient to you.

**Comment by Aschen** [comment]
> Returning the base value of the underlying C struct prevents us from the unnecessary overhead of allocating a new string class where it may not be used, at no cost for the user: `std::string` variables can be instantiated naturally with `const char*` values.
> 
> To me, our getters are correct, we do not need more than that.

For me it's feel weird to have a `const char*` in the middle of a C++ library.  
Even if the user could assign these values to a `std::string` at no cost, he can't do something like this:
```
some_function(search_result.hits + " " + search_result.scroll_id);
```
If we apply your logic everywhere, each SDK method that is returning a `std::string` should return a `const char*`

**Comment by scottinet** [comment]
@Aschen > Agreed for `size_t` vs. `unsigned` without qualifier, it's an obvious mistake. :+1: 

It takes me some effort to come over your argument about strings, which is a blatant example of a [fallacy of composition](https://en.wikipedia.org/wiki/Fallacy_of_composition).
I guess that we can reword that by saying that, for the sake of consistency, all our getters returning strings should do so by returning a `std::string const &` variable. And the getters I mentioned introduce an exception for weak reasons.
I can hear that argument, too.

I propose that we address these matters in a separate, dedicated PR.

**Comment by Aschen** [comment]
Hmm yes you're right, I should have expressed myself differently.
 
> I propose that we address these matters in a separate, dedicated PR.

Ok I will do that.

Concerning this PR, shall we close it ?

**Comment by scottinet** [comment]
If you don't mind, I planned to do it once I've updated the other SDKs, to limit the already large amount of things to adapt.

About this PR however, I agree: we should close it :+1:

**Pull request closed without merging**
