### PR TITLE
Stability fixes -- 1st pass

### PR DESCRIPTION
**Pull request by scottinet**
:warning: depends on https://github.com/kuzzleio/sdk-cpp/pull/55

# Description

Necessary fixes to allow unallocating Kuzzle and Protocol objects at the end of each functional test scenario:

* `document:search` now return a `shared_ptr<SearchResult>` instead of a `SearchResult*`. This allows better memory management for users, especially when using `next`
* `KuzzleEventEmitter`:
  * this class is now abstract instead of being a pure virtual, it now fulfills its role of a base event emitter class, used by both the Kuzzle and Protocol classes
  * implementations found in the Kuzzle and Protocol classes have been aggregated in this new implementation
* `Kuzzle`:
  * the class now properly overrides the necessary KuzzleEventEmitter methods, instead of implementing its own
  * protocol bridging has been removed from that class
* `Protocol`:
  * this abstract class now inherits from `KuzzleEventEmitter`
  * protocol bridging with the Golang world is now done in that class, for a better separation of concern
  * bridge pointers are now handled through smart pointers, to make memory handling safer
* `WebSocket`:
  * the class overrides the necessary KuzzleEventEmitter methods, instead of implementing its own
  * a new destructor has been added to clean up allocated resources (and especially, to close the opened socket)
  * fix a memleak in the `getHost` method

### CODE REVIEW

**Comment by alexandrebouthinon** [comment]
@scottinet: Do you want me to add Valgrind as a Travis build stage? I mean not now but later.

**Comment by scottinet** [comment]
@alexandrebouthinon > this will be needed yes, but we first need to solve all the detected issues.

**Comment by scottinet** [comment]
I'm going to put this branch in WIP: there is a major performance issue with connection/disconnection that I need to investigate

**Comment by scottinet** [comment]
Performance issue resolved: it came from a nasty channel leak in the Golang layer.

**Pull request merged**
